#!/bin/bash

APPNAME="GPG for Mail"

DESCRIPTION="GPG Plugin for Mail.app"

URL='https://gpgtools.org'

HELPSITE='https://gpgtools.tenderapp.com/kb/faq/uninstall-gpg-suite'

FILES=(
    '/Library/Mail/Bundles/GPGMail.mailbundle'
)

uninstall() {
    echo
    echo "AppName: $APPNAME"
    echo "Description: $DESCRIPTION"
    echo "Site: $URL"
    echo "Help page: $HELPSITE"
    echo
    echo "----- BEGIN COMMANDS -----"
    for FILE in "${FILES[@]}"
    do
        echo "sudo rm -rvf '$FILE'"
    done
    echo "------ END COMMANDS ------"
}

$1
